### ISSUE TITLE
Error when blender is closing

### ISSUE THREAD

**Issue by sygi** [Shriinivas/blenderbezierutils#51] opened 2022-01-20 10:33 UTC
When closing blender, I get an error:
```
File ".../blender/2.93/scripts/addons/blenderbezierutils.py", line 10171, in unregisterFlexiBezierKeymaps
    defaultmap = keyconfigs.get("blender").keymaps
AttributeError: 'NoneType' object has no attribute 'keymaps'
```

**Comment by Shriinivas** [comment] 2022-01-21 09:08
The issue is fixed in the latest commit. Please check and let me know if you still face issues.

**Closed by Shriinivas** 2022-01-21 09:08 UTC
