### ISSUE TITLE
Error while dragging a segment

### ISSUE THREAD

**Issue by discodzen** [Shriinivas/blenderbezierutils#19] opened 2020-07-04 17:59 UTC
Blender 2.83 Win8.1

**Comment by Shriinivas** [comment] 2020-07-06 10:02
Can you share your blend file. You can attach it in your message here or send it directly to khemadeva@gmail.com.

**Comment by discodzen** [comment] 2020-07-07 04:02
https://mega.nz/file/0YhjVDLY#HB_A798iMFeXxQqYuWBu7R5_HCCHwFTlJNhFPpFb8N4

**Comment by Shriinivas** [comment] 2020-07-08 11:01
It's a 311 MB file. Can you give me a file with only the objects that are causing the problem.

**Comment by discodzen** [comment] 2020-07-08 17:46
[untitled.zip](https://github.com/Shriinivas/blenderbezierutils/files/4892369/untitled.zip)

**Comment by Shriinivas** [comment] 2020-07-09 09:31
Thanks. The issue is fixed in the latest version. Please check and confirm.

**Comment by discodzen** [comment] 2020-07-10 06:21
I cant install addon.
![изображение](https://user-images.githubusercontent.com/67185296/87123067-bbcadc00-c28e-11ea-9da7-e3ff7800169d.png)

**Comment by Shriinivas** [comment] 2020-07-10 08:52
Sorry about that. Please try with the latest version.

**Comment by discodzen** [comment] 2020-07-11 04:14
Works fine. Thanks!
And
If it is possible. Addon requires improved performance.
https://www.youtube.com/watch?v=zrFcHUBiYRk

**Comment by Shriinivas** [comment] 2020-07-11 07:57
Yes, performance can sometimes be a problem, especially if there are lot of curve segments.
You can try decreasing the 'Display Curve Resolution' from the add-on preferences to see if that helps.

**Closed** 2020-07-12 11:19 UTC
