### ISSUE TITLE
Bezier tools cause the Measure & Annotation tools to disappear when using Blender templates

### ISSUE THREAD

**Issue by Ekstrarandom** [Shriinivas/blenderbezierutils#10] opened 2020-01-07 14:15 UTC
**Issue:**
When using e.g. the Blender Sculpt template (or any other template) the Measure & Annotation tools in the toolbar in Object Mode disappear when Bezier Tools is installed.

**Steps:**
1) Download and extract a new zip copy of Blender 2.81a
2) Install & activate Bezier Tools 
(note there are 8 tools above the 2 Bezier tools)
3) Go to File > New > Sculpting
4) While in the Sculpt Template go from Sculpt Mode > Object Mode
(note there are now 7 tools above the 2 Bezier tools - the Measure Tool has disappeared)
5) Now go to File > New > General
(note there are now only 6 tools above the 2 Bezier tools - both the Annotation & Measure Tools have disappeared)
6) Uninstall Bezier Tools
(note that the 2 tools are still missing)
7) Close Blender & restart
(note that these 2 tools behave now in a normal fashion when you use any template)

**Notes:** 
A) This issue only occurs after Bezier Tools is installed 
(blenderbezierutils.py downloaded on 07/01/20)
B) Bezier Tools is the only add-on that is installed / activated
C) It only involves the Annotate & Measure tools 

**My System:**
OS: Windows 10 Pro v1909
Processor: AMD Ryzen 5 3600 6-core
RAM: 32 GB
Graphics Card: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2/4.5.0 NVIDIA 441.66 (latest Studio driver)
Blender: Portable 2.81a

Thank you for your wonderful add-on, it will make working with curves much more pleasurable!

**Comment by Shriinivas** [comment] 2020-01-08 04:21
Appreciate the detailed bug report! 
The issue is fixed in the latest version. Kindly check and confirm.

**Comment by Ekstrarandom** [comment] 2020-01-08 08:41
Thank you for your super-fast response and fix!

I can confirm that the issue was resolved - the tools behave as expected in
the default Blender templates as well as in my own custom templates.

The functionality of the add-on and the time and dedication that you
clearly put into the development of this add-on are outstanding, thank you.

**Comment by Shriinivas** [comment] 2020-01-08 08:46
Thank you for the appreciation :)

**Closed by Shriinivas** 2020-01-08 08:46 UTC
