### ISSUE TITLE
Control Z after flexi edit bezier

### ISSUE THREAD

**Issue by BW2001** [Shriinivas/blenderbezierutils#14] opened 2020-02-25 22:11 UTC
Not sure of the exact circumstances but after typing in values for a vertex position in flexi edit I did a control Z

![undo vertex move by typing](https://user-images.githubusercontent.com/61478602/75291838-ec980080-581a-11ea-86be-e75702674eba.png)

**Comment by Shriinivas** [comment] 2020-02-26 04:47
Thank you for reporting the issue. To reproduce the error you can follow these steps:
1) Create a curve consisting of two straight segments with Flexi Draw
2) Double click the common Bezier point between the two segments.
3) Type a value (like '2') on keyboard 
4) Press Ctrl+Z

The issue is fixed in the latest version. Kindly confirm the fix.

**Comment by BW2001** [comment] 2020-02-26 22:39
I can confirm it now works but I still get the error from my previous report – see attached. I still use windows 7 -  I will check on windows 10 later – it shouldn’t matter all other software running fine.

**Comment by Shriinivas** [comment] 2020-02-27 03:12
Closing this issue. The other problem is tracked through another issue (https://github.com/Shriinivas/blenderbezierutils/issues/13)

**Closed by Shriinivas** 2020-02-27 03:12 UTC

**Comment by BW2001** [comment] 2020-03-26 22:55
Playing around with spline options. Had another error with setting vertex type via S pie menu – see attached

**Comment by Shriinivas** [comment] 2020-03-27 04:45
I did not get the attachment. I suggest you go to this page: 
https://github.com/Shriinivas/blenderbezierutils/issues 
Then create a new issue and add the attachment there.
