### ISSUE TITLE
W key conflict with "Select Box" in Flexi edit mode

### ISSUE THREAD

**Issue by rajq123** [Shriinivas/blenderbezierutils#37] opened 2020-12-02 00:34 UTC
Please either enable the option to change hotkey or Change the W key with another key.

**Comment by Shriinivas** [comment] 2020-12-03 09:30
This is duplicate of #35. Hotkeys are configurable you can change the W hotkey to any other key from add-on preferences.

**Closed by Shriinivas** 2020-12-03 09:30 UTC
